== Nashorn JavaScript Engine from within Java

The Nashorn Engine is a JavaScript implementation of the https://www.jcp.org/en/jsr/detail?id=223[JSR-223] _(Scripting for the Java Platform)_. It implements the `javax.script` API.
So, for being able to evaluate JavaScript code from Java, we just create a new Nashorn `javax.script.ScriptEngine`.

[source,java]
----
ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");<1>
engine.eval("print('Hello World');");
----
<1> The Nashorn engine names you can use here are _"nashorn"_, "javascript"_ and _"js"_.

As seen above, JavaScript code can be evaluated directly by passing it as a string to the `eval()` method of the engine object.
Alternatively you can parse (and evaluate) a `.js`-file by passing a `FileReader` object pointing to your file:

[source,java]
----
ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");
engine.eval(new FileReader("test.js"));
----


=== Invoking JavaScript functions from Java

It's not only possible to run single JS statements or evaluate complete JS files, but it's also possible to invoke JavaScript functions from within Java code.
Additionally you can pass Java objects as function arguments and return data back from the function to the calling Java method.

Let's assume our JavaScript file:

[source,javascript]
.example.js
----
var sayHello = function(name) {
  print('Hello, ' + name + '!');
  return 'hello from javascript';
};
----

To be able to call our defined `sayHello` function, we first have to cast the `engine` object to the `Invocable` interface, which is implemented by the `NashornScriptEngine` implementation.
The `Invocable` interface provides the `invokeFunktion()` method, which allows to call JavaScript functions for a given name and pass arguments:

[source,java]
----
ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");
engine.eval(new FileReader("example.js"));

// cast the script engine to an invocable instance
Invocable invocable = (Invocable) engine;

Object result = invocable.invokeFunction("sayHello", "John Doe");
System.out.println(result);
System.out.println(result.getClass());

// Hello, John Doe!
// hello from javascript
// class java.lang.String
----

Our code prints three lines to the console: The JavaScript function `print()` pipes the result to `System.out`, afterwards, the two Java `System.out.println()` methods are evaluated.


=== Invoking Java methods from JavaScript

Calling or invoking Java methods from JavaScript code is just as easy as vice-versa. Let's assume a Java class with two methods:

[source,java]
.MyJavaClass.java
----
package my.package;

public class MyJavaClass {

    public static String sayHello(String name) {
        return String.format("Hello %s from Java!", name);
    }

    public int add(int a, int b) {
        return a + b;
    }

}
----

Our Java class can be referenced from JavaScript via the `Java.type` API extension. This is similar to the `import` statement in Java.
After referencing our Java class, we can call the static method and print the result to `System.out`.
Since the `sayHello()` method is static, we don't have to create an instance as we have to do for calling the `add()` method.

[source,javascript]
----
var MyJavaClass = Java.type('my.package.MyJavaClass');

// call the static method
var greetingResult = MyJavaClass.sayHello('John Doe');
print(greetingResult);

// create a new intance of MyJavaClass
var myClass = new MyJavaClass();
var calcResult = myClass.add(1, 2);
print(calcResult);

// Hello John Doe from Java!
// 3
----


==== Nashorn type conversions

With this little example, you can find out, how Nashorn handles type conversions between Java and JavaScript, when calling Java methods from JavaScript.

[source,java]
----
public static void printType(Object object) {
    System.out.println((object.getClass());
}
----

Now, call this static method with different JavaScript types:

[source,javascript]
----
MyJavaClass.printType('Hello');
// class java.lang.String

MyJavaClass.printType(123);
// class java.lang.Integer

MyJavaClass.printType(12.34);
// class java.lang.Double

MyJavaClass.printType(true);
// class java.lang.Boolean

MyJavaClass.printType(new Number(123));
// class jdk.nashorn.internal.objects.NativeNumber
// class jdk.nashorn.api.scripting.ScriptObjectMirror

MyJavaClass.printType(new Date());
// class jdk.nashorn.internal.objects.NativeDate
// class jdk.nashorn.api.scripting.ScriptObjectMirror

MyJavaClass.printType(new RegExp());
// class jdk.nashorn.internal.objects.NativeRegExp
// class jdk.nashorn.api.scripting.ScriptObjectMirror

MyJavaClass.printType({foo: 'bar'});
// class jdk.nashorn.internal.scripts.J04
// class jdk.nashorn.api.scripting.ScriptObjectMirror
----

- Primitive JavaScript types are converted to the appropriate Java wrapper class.
- Native JavaScript objects are represented by internal adapter classes, respectively to `ScriptObjectMirror`.

IMPORTANT: Don't rely on programming against / using internal classes in `jdk.nashorn.internal` as they are likely subject to change!


=== ScriptObjectMirror

The `ScriptObjectMirror` is part of the `jdk.nashorn.api` and is intended to be used in client-code instead of the internal classes.
This mirror object is a representation of the underlying JavaScript object and provides access to it and its methods and properties.
The `ScriptObjectMirror` implements the `Map` interface.

We edit our last method slightly to

[source,java]
----
public static void printObjectMirror(ScriptObjectMirror mirror) {
    System.out.println(mirror.getClassName() + ": " + Arrays.toString(mirror.getOwnKeys(true)));
}
----

When we call this method now with our last four JS function calls (number, date, regexp and object literal):

[source,javascript]
----
MyJavaClass.printType(new Number(123));
MyJavaClass.printType(new Date());
MyJavaClass.printType(new RegExp());
MyJavaClass.printType({
    foo: 'bar',
    bar: 'foo'
});
----

we now get this result:

[source]
----
Number: []
Date: []
RegExp: [lastIndex, source, global, ignoreCase, multiline]
Object: [foo, bar]
----

Also, we can call member functions on JavaScript objects from Java. +
Let's assume a JavaScript type `Person` with some properties and a function `getFullName()`.

[source,javascript]
----
function Person(firstName, lastName) {
  this.firstName = firstName;
  this.lastName = lastName;
  this.getFullName = function() {
    return this.firstName + ' ' + this.lastName;
  }
}
----

The function `getFullName()` can be called on `ScriptObjectMirror` via `callMember()`:

[source,java]
----
public static void getFullName(ScriptObjectMirror person) {
    System.out.println("Full name is: " + person.callMember("getFullName"));
}
----

Now, our JavaScript code looks like this:

[source,javascript]
----
var person = new Person('John', 'Doe');
MyJavaClass.getFullName(person);

// Full name is: John Doe
----


=== Options for the script engine

Nashorn script engine customization can be done by using `nashorn.args` system properties.
Just specify the options you want with `*-Dnashorn.args=...*`
E.g. enabling the scripting mode:

[source,bash]
----
$ java -Dnashorn.args=-scripting MyJavaClass
----

You can also create a Nashorn engine by passing customization options programmatically.
In this case, you'll have to instantiate `NashornScriptEngineFactory` directly:

[source,java]
----
NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
ScriptEngine engine = factory.getScriptEngine(new String[] { "-scripting" });
----

TIP: Available options can be determined from the link:#_nashorn_at_the_command_line_interface_cli[command line] when calling `jjs -help`.


=== Bindings / Context

A `ScriptContext` contains one or more bindings, each associated to a scope. By default, there are two scopes:

- `ENGINE_SCOPE`
- `GLOBAL_SCOPE`

When a Nashorn engine is created, it creates a default context:

[source,java]
----
ScriptContext defaultContext = engine.getContext();
----

The default context's `ENGINE_SCOPE` is the scope where ECMAScript "global" objects and functions (`Object`, `Function`, `Math`, `RegExp`, `parseInt`, etc.) are stored.
The `GLOBAL_SCOPE` is shared between all engines created by the same `ScriptEngineManager`.

You can store variables in the context (use of the scope is optional, default is `ENGINE_SCOPE`):

[source,javascript]
----
ScriptContext context = engine.getContext();
// stores an object under the key `myKey` in the (engine scoped) context
context.setAttribute("myKey", object, ScriptContext.ENGINE_SCOPE);
// retrieves the object with key `myKey` from (engine scoped) context
context.getAttribute("myKey", ScriptContext.ENGINE_SCOPE);

Bindings b = context.getBindings(ScriptContext.ENGINE_SCOPE);
b.get("Object");    // gets ECMAScript "Object" constructor
b.get("undefined"); // ECMAScript 'undefined' value
----



If a variable is not found in `ENGINE_SCOPE`, `GLOBAL_SCOPE` bindings are being searched.

WARNING: There's a confusion due to ECMAScript "global" properties being in `ENGINE_SCOPE` (toplevel _"this"_ in script) and not in `GLOBAL_SCOPE`.

---

NOTE: More on ScriptContexts and Bindings: https://wiki.openjdk.java.net/display/Nashorn/Nashorn+jsr223+engine+notes

